### ISSUE TITLE
펀딩 페이지 - 펀딩 아이템 컴포넌트 구현

### ISSUE THREAD

**Issue by devkyoung2** [KakaoFunding/front-end#118]
### 작업 상세 내용

- [x] 상품 컴포넌트 구현
- [x] 펀딩 결제기능 구현(본인이 본인에게 펀딩)
- [x] 펀딩 취소 기능 구현

### 주의사항
- 상품 클릭시 상품 상세 정보 이동
- 브랜드 클릭시 브랜드 페이지로 이동
- 펀딩하기 버튼 클릭시 펀딩결제 페이지로 이동
- 펀딩 취소 시 모달창을 띄워 주의사항 안내

## 참고할만한 자료
![image](https://github.com/KakaoFunding/front-end/assets/79066587/8dd93e5f-fbec-4120-ad35-7f0ddf67c491)

**Comment by uraflower** [comment]
1. 이름 변경 제안: 상품 컴포넌트 -> 펀딩 아이템 컴포넌트
2. task에서 `펀딩 등록 기능`은 상품 상세 조회 페이지에서 이루어집니다. `펀딩 결제(본인이 본인 펀딩을 결제하는 것) 기능`으로 수정해야 하지 않을까용?
