### ISSUE TITLE
펀딩 페이지 - 펀딩 진행률 컴포넌트 구현

### ISSUE THREAD

**Issue by devkyoung2** [KakaoFunding/front-end#119]
### 작업 상세 내용

- [x] 펀딩 정보 띄우기
- [ ] 프로그레스바 구현 #125 

### 주의사항
- 펀딩 진행률은 소수점 둘째 자리에서 반올림한다.

## 참고할만한 자료

![image](https://github.com/KakaoFunding/front-end/assets/79066587/9e60e772-399a-499d-a1a8-c34a075725f0)

**Comment by uraflower** [comment]
이 컴포넌트를 다른 페이지에서도 사용하니까, 이슈 제목을 바꾸는 게 어떨까용?
