### ISSUE TITLE
선물함 페이지 - 사용가능 선물 탭 컴포넌트 구현

### ISSUE THREAD

**Issue by uraflower** [KakaoFunding/front-end#188]
### 작업 상세 내용

- [ ] 사용가능 선물 탭 구현
- [ ] 무한 스크롤 적용 (페이지 사이즈: 20)

### 주의사항

- 선물 상세 조회 페이지 구현 전까지, **선물 클릭 시 상품 상세 조회 페이지로 이동**

## 참고할만한 자료

![Image](https://github.com/KakaoFunding/front-end/assets/82873315/3bdb91a9-38d3-4487-99c4-aa3477e35fa9)

**Comment by devkyoung2** [comment]
선물상품 컴포넌트를 이슈 분리하는게 좋을 것 같아요. 사용완료탭에서도 사용되니까요..!!
