### ISSUE TITLE
펀딩 내역 페이지 디자인

### ISSUE THREAD

**Issue by devkyoung2** [KakaoFunding/front-end#232]
### 작업 상세 내용

- [x] 펀딩 내역 페이지 디자인 : ”상태“ 를 통한 필터링 고려
  - 상태 : 취소, 완료, 진행 중 ~~(진행 중이 필요한지 모르겠습니다... 펀딩내역은 펀딩이 취소되거나, 완료된 상품만 보여주는것이 맞는것같은데 코멘트 부탁드립니다.)~~
- [x] 펀딩 내역 페이지 이슈 생성

### 주의사항
- 아래의 디자인을 참고하되, 어떤상품을, 누구에게, 얼마를 기여했는지에 대한 정보가 들어갈 것
- 디자인이 완료되면 펀딩 내역 관련 이슈를 생성하고, 해당 이슈를 닫아주세요

## 참고할만한 자료
![image](https://github.com/KakaoFunding/front-end/assets/79066587/4f529263-57b3-488f-8c2d-4106d7a7e8c5)

**Comment by uraflower** [comment]
저는 진행중인 펀딩도 펀딩 내역에 들어가야 한다고 생각해요. 만약 취소/완료된 펀딩만 펀딩 내역에 들어간다면, 친구의 펀딩에 기여를 했을 때 친구의 펀딩이 취소/완료되지 않은 경우 "내가 참여한 친구의 펀딩 내역" 탭에서 기여한 사실을 확인하지 못하는 경우가 생길 것 같아요.

펀딩 아이템을 등록한 시점부터 펀딩 내역에 있어야 한다고 생각하는데... 이 부분은 다들 생각이 다를 수도 있을 것 같네요.

저희 의견이 좁혀지지 않거나 잘 모르겠으면 데이터를 주는 입장인 백엔드 분들과 더 얘기해도 좋을 것 같습니다.

**Comment by devkyoung2** [comment]
@uraflower 듣고보니 그렇네요...... 친구의 펀딩에 기여했을 경우 펀딩내역을 이 페이지에서 밖에 조회를 못하겠네요!  민우님이 확인하셔야 하니까 제 의견은 지우지 않고 취소선으로 바꾸겠습니다.
