### ISSUE TITLE
메인 페이지 - 무한스크롤 상품 리스트 아이템 컴포넌트 구현

### ISSUE THREAD

**Issue by devkyoung2** [KakaoFunding/front-end#233]
### 작업 상세 내용

- [x] 상품 썸네일 띄우기
- [x] 상품 정보 띄우기
- [x] 장바구니/위시 버튼 띄우기

### 주의사항
- 각 상품 클릭시 상품 상세조회페이지로 이동
- 상품 목록 조회 페이지에서 사용한 상품 아이템 컴포넌트를 재사용한다.

## 참고할만한 자료
![image](https://github.com/KakaoFunding/front-end/assets/79066587/73cd152a-55b3-4b53-a278-77c823d48f2a)

**Comment by uraflower** [comment]
이 컴포넌트는 상품 목록 조회 페이지에서 사용한 상품 아이템 컴포넌트와 아주 유사한 것 같아요. `가격`과 `선물/위시 버튼` 사이 여백만 다른 것 같네요.
당장은 구현이 급하니까 기존에 있었던 컴포넌트를 복붙하고 여백만 바꿔서 사용하면 좋을 것 같고... 추후에 프로덕트 아이템 관련해서 전부 리팩토링하면 좋겠네요.. ㅠㅠ

**Comment by devkyoung2** [comment]
@uraflower  이슈 주의사항에 추가하겠습니다.
