### ISSUE TITLE
탭 목록 컴포넌트 구현

### ISSUE THREAD

**Issue by uraflower** [KakaoFunding/front-end#3]
## 참고할만한 자료(선택)

![Image](https://github.com/KakaoFunding/back-end/assets/82873315/e5113f10-e2f4-43f6-8ed1-6c4ca72ff06b)
![Image](https://github.com/KakaoFunding/back-end/assets/82873315/4a8c0dce-fa5a-4b10-aff2-4d7137bc0f1d)

**Comment by ohgus** [comment]
해당 컴포넌트는 상품 목록 조회 페이지에서도 재사용 가능해 보이네요!



![Image](https://github.com/KakaoFunding/front-end/assets/123801385/dd047582-2104-438f-9911-bbd5e589fd01)

**Comment by ohgus** [comment]
랭킹 페이지에 있는 탭은 조금 모양이 다른데 하나로 통일하는 것은 어떻게 생각하시나요?



![Image](https://github.com/KakaoFunding/front-end/assets/123801385/70b400f4-4e2a-4bc4-8982-3c4eba5affe9)

**Comment by uraflower** [comment]
> 랭킹 페이지에 있는 탭은 조금 모양이 다른데 하나로 통일하는 것은 어떻게 생각하시나요?
> 
> ![Image](https://private-user-images.githubusercontent.com/123801385/305643491-70b400f4-4e2a-4bc4-8982-3c4eba5affe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxODU1NDMsIm5iZiI6MTcwODE4NTI0MywicGF0aCI6Ii8xMjM4MDEzODUvMzA1NjQzNDkxLTcwYjQwMGY0LTRlMmEtNGJjNC04OTgyLTNjNGViYTVhZmZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxN1QxNTU0MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjEwOTIyOTQwNTE2ZTYzNTU3ZGJlYmUwZjQ2Mjk2YzZmOTMxMTEzNWU4ODYxYTc5Y2UxNjJmMjg3NjJkYjE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yN9I31Qd58GVgfW-ceesIeFJu5wljC0WQBvrS9MaMvg)

`랭킹 페이지 - 받고 만족한`에 있는 탭 말씀하시는 것 같은데, `받고 만족한`은 안하기로 했으니 괜찮을 것 같아요!
