### ISSUE TITLE
상품 아이템 컴포넌트 구현 (세로)

### ISSUE THREAD

**Issue by ohgus** [KakaoFunding/front-end#6]
### 작업 상세 내용

- [x] 상품 썸네일
- [x] 상품 이름
- [x] 상품 가격
- [x] 장바구니 버튼
- [x] 위시 버튼 (10,000이 넘어가면 1만+, 1.2만+ 같은 식으로 보여짐)
- [x] 브랜드명

## 참고할만한 자료

![Image](https://github.com/KakaoFunding/front-end/assets/123801385/9ec1a5e1-1ca0-4408-a8e7-bcac7f1d4551)

![Image](https://github.com/KakaoFunding/front-end/assets/123801385/13f49e9d-5e47-4699-a648-1173d3223617)

**Comment by uraflower** [comment]
상품 아이템들이 다 다르게 생겼는데 구성은 동일한 것 같더라구요.
- `상품 썸네일`
- `link info`: 브랜드명, 상품명, 가격 포함. 경우에 따라 브랜드명이나 가격이 빠지기도 하는 듯
- 'util info`: 선물하기 버튼, 위시 버튼 포함. 경우에 따라 아예 빠지거나 일부 버튼이 빠지기도 함

그래서 상품 아이템 컴포넌트를 특정 페이지에 속하지 않는 공용 컴포넌트로 구현하는 것은 어떨까요?
아래는 참고 사진입니다.

![Image](https://github.com/KakaoFunding/front-end/assets/82873315/7d6ba121-e69d-4a9d-9e99-de5e6de3a417)

**Comment by ohgus** [comment]
좋은 아이디어 같습니다! 그럼 랭킹을 비롯해서 모든 아이템 컴포넌트를 통일 하자는 말씀이신거죠?

**Comment by uraflower** [comment]
네! 그럼 요 이슈도 수정되어야 할 것 같아요
