### ISSUE TITLE
헤더와 푸터가 예상한 디자인과 다름

### ISSUE THREAD

**Issue by uraflower** [KakaoFunding/front-end#70]
## 버그 설명

헤더와 푸터가 예상한 디자인과 다름

## 버그 발생 상황

- 헤더가 상단에 고정되지 않음
- 헤더 테두리 추가가 필요함
- 푸터가 하단에 고정되지 않음
- 윈도우 사이즈를 줄였을 때, 푸터 크기가 작아짐
- 메인 콘텐츠를 넣었을 때, 헤더/푸터와 겹침

## 예상 결과

- 헤더가 상단에 고정됨
- 헤더 테두리 bottom이 추가됨
- 푸터가 하단에 고정됨
- 윈도우 사이즈를 조절해도 푸터 넓이가 작아지지 않음
- 메인 콘텐츠를 넣었을 때, 헤더/푸터와 겹치지 않음

## 참고할만한 자료

- 푸터 넓이가 다른 모습
  ![Image](https://github.com/KakaoFunding/front-end/assets/82873315/e925616e-e73e-4c31-9cd1-f2b1e3aff243)

- 푸터가 하단에 고정되지 않는 모습 & 메인 콘텐츠(색상 칠해진 곳)과 헤더/푸터가 겹치는 모습
  ![Image](https://github.com/KakaoFunding/front-end/assets/82873315/f57f7235-8261-4c80-af53-0646e922b97f)

**Comment by devkyoung2** [comment]
`border-bottom: 1px solid #f5f5f5`

저도 이거 확인하고 컴포넌트 좀 확인해봤는데 `innerheader`에 이 코드 넣으니까 딱맞았었습니다!

**Comment by ohgus** [comment]
헤더 테두리는 제가 피그마 컴포넌트만 보고 하다 보니 놓친거 같네요...
그리고 헤더와 푸터 위치는 어떤 상황에서 위치가 변경되는지 알 수 있을까요? 제 컴퓨터에서는 변경사항을 적용하기 이전에도 위치가 고정이 되고 있는데... 제가 어떤 부분을 놓친건지 궁굼해서요...

**Comment by uraflower** [comment]
피그마 컴포넌트에도 테두리 되어 있는데, 피그마 배경 색이랑 헤더 배경 색상이랑 비슷비슷하다보니 미처 못 보신 것 같네요. 😄 

첫 번째 사진은 창 넓이를 줄였을 때 푸터가 일그러지는 건데, 이건 #71 PR에서 커밋 확인해보시는 게 좋을 것 같아요.
두 번째 사진 보시면 메인 콘텐츠(색 칠해진 영역)이 헤더 안으로 들어간 거 보이시죠? 헤더가 메인 콘텐츠랑 겹쳐지고 있습니다.
또 푸터가 바닥에 붙어있지 않고 스크롤함에 따라 위로 올라오고 있습니다. 푸터가 메인 콘텐츠랑 겹쳐지는 거죠.

저도 처음에 pull 해서 봤을 땐 위치가 잘 고정된 것처럼 보였는데,
윈도우 사이즈 줄이니까 깨지길래, 메인 콘텐츠 넣어도 깨지려나 싶어서 넣어보다가 알게 되었습니다.

**Comment by ohgus** [comment]
@uraflower 
Footer의 위치의 경우 제가 카카오의 css를 따라서 position: absolute를 주었는데요. 해당 부분을 삭제하면 푸터가 컨텐츠 다음으로 잘 적용이 되는 것 같은데 어떻게 생각하시나요?

**Comment by uraflower** [comment]
@ohgus 
width: 100% 줘도 윈도우 사이즈 줄이면 상위 요소 width가 작아져서 그만큼 푸터가 비지 않나요? 1번 사진처럼요. 윈도우 사이즈 줄이고 가로 스크롤 해봤을 때 비어있었던 것 같아요.
근데 제가 아까 수정할 때의 기억을 말씀드리는 거라 정확하지 않을 수도 있으니 참고만 해주세용..!

**Comment by ohgus** [comment]
제 컴퓨터에서는 1번 사진과 같은 문제가 발견이 안되서 어떤 부분을 수정해야 하는 건지 진짜 모르겠네요...
