### ISSUE TITLE
카테고리 배경색 미지정

### ISSUE THREAD

**Issue by devkyoung2** [KakaoFunding/front-end#75]
## 버그 설명
카테고리의 `background-color` 속성이 미지정되어 있어 중첩된 요소가 겹쳐져 보임

## 버그 발생 상황
- 카테고리 호버시 드롭다운이 열리면서 메인 콘텐츠와 겹쳐짐

## 예상 결과
- 카테고리 호버시 드롭다운이 메인 콘텐츠와 겹쳐지지 않음

## 참고할만한 자료
![image](https://github.com/KakaoFunding/front-end/assets/79066587/d0d75496-70e1-412d-ba11-7ebb3106bf8c)

**Comment by uraflower** [comment]
요거 실제로 그러한진 모르겠고 제 추측이지만, 배경색 말고도 z-index 지정이 안 된 것도 연관이 있을 것 같아요.
아마 제가 구현할 때 지정을 안 했을 거예요..!

그래서 #76 이랑 하나의 이슈로 묶어서 해결하는 건 어떨까용?

**Comment by devkyoung2** [comment]
@uraflower 카테고리 코드 확인해봤는데 배경색이 없어서 단순히 배경색 오류인줄 알았네요 !! z-index로 해결된다면 두개 묶어서 오늘 내로 해결하겠습니다~
